#!/usr/bin/env python3
"""Embed the ComfyUI plugin archive into the happ as base64 bytes.

A happ cannot read its own bundled files: the host serves documents with
`connect-src 'none'`, so both `fetch("./app/assets/x")` and `XMLHttpRequest` are
refused. The archive therefore travels as a script that hangs the bytes on the
namespace, and the settings dialog feeds them to the host file writer, which hands
the user the system save dialog. What lands on disk is byte-for-byte the archive
`release/vibedraw-comfyui-plugin-v<version>.zip` holds — nothing is downloaded.

The version comes from tools/package-plugin.py so the two stay in step.

Usage:
  python3 tools/embed-plugin.py           # rewrite app/assets/comfyui-plugin.js
  python3 tools/embed-plugin.py --check   # verify the committed asset matches the archive
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
PACKAGER = ROOT / "tools" / "package-plugin.py"
OUTPUT = ROOT / "app" / "assets" / "comfyui-plugin.js"
LINE_CHARS = 96


def plugin_version() -> str:
    match = re.search(r'^VERSION = "([^"]+)"', PACKAGER.read_text(encoding="utf-8"), re.MULTILINE)
    if not match:
        raise SystemExit(f"no VERSION found in {PACKAGER.relative_to(ROOT)}")
    return match.group(1)


def archive_path() -> pathlib.Path:
    return ROOT / "release" / f"vibedraw-comfyui-plugin-v{plugin_version()}.zip"


def render(archive: pathlib.Path) -> str:
    payload = archive.read_bytes()
    digest = hashlib.sha256(payload).hexdigest()
    encoded = base64.b64encode(payload).decode("ascii")
    chunks = [encoded[at : at + LINE_CHARS] for at in range(0, len(encoded), LINE_CHARS)]
    body = " +\n".join(f'    "{chunk}"' for chunk in chunks)
    return (
        "// Generated by tools/embed-plugin.py from "
        f"{archive.relative_to(ROOT).as_posix()} — do not edit by hand.\n"
        "// A happ cannot read its own bundled files (the host serves documents with\n"
        "// connect-src 'none'), so the plugin archive is carried as bytes and written out\n"
        "// through the host when the user saves it.\n"
        "(function (app) {\n"
        '  "use strict";\n'
        "  app.comfyuiPlugin = {\n"
        f'    name: "{archive.name}",\n'
        f"    bytes: {len(payload)},\n"
        f'    sha256: "{digest}",\n'
        "    base64:\n" + body + "\n"
        "  };\n"
        "})(window.vibedraw);\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify the committed asset")
    args = parser.parse_args()

    archive = archive_path()
    if not archive.is_file():
        raise SystemExit(f"missing archive: {archive.relative_to(ROOT)}")
    content = render(archive)

    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit("app/assets/comfyui-plugin.js does not match the plugin archive")
        print(f"embedded plugin ok {OUTPUT.relative_to(ROOT)} bytes={archive.stat().st_size}")
        return

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"created {OUTPUT.relative_to(ROOT)} from {archive.name} ({archive.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
